[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_program = "45hsoS2FUKk3iaLnqqtaP6BLCTaBogPBgLUKukQdztwg"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
